version: '3.8'
services:
  t2gdb:
    container_name: agendadb
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agenda
    ports:
      - '5436:5432'
    volumes:
      - agendadata:/var/lib/postgres

  t2gpgadmin:
    container_name: pgadmin_agenda
    image: dpage/pgadmin4
    depends_on:
      - t2gdb
    ports:
      - '5052:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
  
  agendaserver:
    container_name: agendaserver
    depends_on:
      - agendapgadmin
    build: ./
    restart: unless-stopped
    ports:
      - '4200:4200'
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
  agendadata: