### Create Event
POST http://localhost:3000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MGQ1MjFlMi05YzcwLTRjNjUtYjY3MS1mNWJjNjExZGVlZTQiLCJpYXQiOjE3MjEzODgxNDMsImV4cCI6MTcyMTM5MTc0M30.LEFkjzZVrU2QGmWcFyA_8AOT76ILGVcUU2Vs8Mn24fE

{
  "title": "Concert",
  "description": "An amazing music concert",
  "startDateTime": "2024-08-20T18:00:00Z",
  "endDateTime": "2024-08-20T21:00:00Z",
  "venueId": "60a8bd83-f19e-4b30-9e51-6a081d0a8965",
  "organizerId": "022e5400-1ef4-4457-91b8-0950c6ba6afd",
  "categoryId":"3b1c6662-8f98-4096-92a8-e47aeda8019a",
  "images": ["https://www.pinterest.com/pin/683562049715830733/", "https://i.pinimg.com/474x/ce/8f/21/ce8f21c54b10d1c24960dd6a517f2206.jpg"]
}


### Get All Events
GET http://localhost:3000/events


### Get Event by ID
GET http://localhost:3000/events/da9edcb9-7d42-4227-aad5-5dd224faaea0


### Update Event
PUT http://localhost:3000/events/da9edcb9-7d42-4227-aad5-5dd224faaea0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MGQ1MjFlMi05YzcwLTRjNjUtYjY3MS1mNWJjNjExZGVlZTQiLCJpYXQiOjE3MjEzODgxNDMsImV4cCI6MTcyMTM5MTc0M30.LEFkjzZVrU2QGmWcFyA_8AOT76ILGVcUU2Vs8Mn24fE

{
  "title": "Updated Concert",
  "description": "An updated amazing music concert",
  "startDateTime": "2024-07-20T18:00:00Z",
  "endDateTime": "2024-07-20T21:00:00Z",
  "venueId": "60a8bd83-f19e-4b30-9e51-6a081d0a8965",
  "organizerId": "022e5400-1ef4-4457-91b8-0950c6ba6afd"
}


### Cancel an event
DELETE http://localhost:3000/events/da9edcb9-7d42-4227-aad5-5dd224faaea0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MGQ1MjFlMi05YzcwLTRjNjUtYjY3MS1mNWJjNjExZGVlZTQiLCJpYXQiOjE3MjEzODgxNDMsImV4cCI6MTcyMTM5MTc0M30.LEFkjzZVrU2QGmWcFyA_8AOT76ILGVcUU2Vs8Mn24fE

### Get all events for organizer
GET http://localhost:3000/events/organizer/022e5400-1ef4-4457-91b8-0950c6ba6afd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMjJlNTQwMC0xZWY0LTQ0NTctOTFiOC0wOTUwYzZiYTZhZmQiLCJpYXQiOjE3MjEzNjg3ODYsImV4cCI6MTcyMTM3MjM4Nn0.61aR_WPBR52cqEGYXpx6MK2ji97IcTn1m2msa0hqy0U



### Get all events for user
GET http://localhost:3000/events/user/5232e85e-0934-4b8a-8eec-5eab548dfc9f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMjJlNTQwMC0xZWY0LTQ0NTctOTFiOC0wOTUwYzZiYTZhZmQiLCJpYXQiOjE3MjEzMTM0MDIsImV4cCI6MTcyMTMxNzAwMn0.1wqRUbxB6FoWrec4iLZDJFeYKRXB1UMZuya1UDv1kH4