### Create Venue
POST http://localhost:3000/venues
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOGQ4NjFkOS1mMjhkLTQxZjQtYjkyNC05M2M1OGQ4NTkyNGMiLCJpYXQiOjE3MjEzMDg3MTAsImV4cCI6MTcyMTMxMjMxMH0.uyS08qfZP8_XgC87xTahPVDKYUuPEAlzT6frYxJZ-sI

{
  "name": "Conference Center",
  "address": "123 Main St, Cityville",
  "capacity": 500
}

### Get All Venues
GET http://localhost:3000/venues

### Get Venue by ID
GET http://localhost:3000/venues/31626e66-d517-4a9f-bcda-7eb7168d2d6f


### Update Venue
PUT http://localhost:3000/venues/d9ef21e8-973b-483d-8118-8eb27b327a1e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOGQ4NjFkOS1mMjhkLTQxZjQtYjkyNC05M2M1OGQ4NTkyNGMiLCJpYXQiOjE3MjEzMDg3MTAsImV4cCI6MTcyMTMxMjMxMH0.uyS08qfZP8_XgC87xTahPVDKYUuPEAlzT6frYxJZ-sI

{
  "name": "Updated Conference Center",
  "address": "123 Main St, Cityville",
  "capacity": 600
}


### Delete Venue
DELETE http://localhost:3000/venues/31626e66-d517-4a9f-bcda-7eb7168d2d6f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxOGQ4NjFkOS1mMjhkLTQxZjQtYjkyNC05M2M1OGQ4NTkyNGMiLCJpYXQiOjE3MjEzMDg3MTAsImV4cCI6MTcyMTMxMjMxMH0.uyS08qfZP8_XgC87xTahPVDKYUuPEAlzT6frYxJZ-sI